# config/deploy.yml
service: artryazanov-website
image: artryazanov/artryazanov-website # Your image name in GHCR

# Specify the user for SSH connections (hidden via ERB)
ssh:
  user: <%= ENV['DEPLOY_USER'] %>

# Credentials for GitHub Container Registry
registry:
  server: ghcr.io
  username: artryazanov
  password:
    - KAMAL_REGISTRY_PASSWORD

# Build settings
builder:
  arch: amd64

# Common environment variables (if needed)
env:
  clear:
    # You can add public variables here
  secret:
    # Secrets (e.g., tokens) go here


